/**
 * Generated by HyperIndex codegen. Do not edit manually.
 * Wires project-specific types into the `envio` module.
 * Regenerate with `pnpm codegen` (`envio codegen`).
 */
/// <reference path="./generated/index.d.ts" />
